// let a = 81
//     b = 17
// console.log(a / b)
// console.log(a + b)
// console.log(a - b)
// console.log(a = b)
// console.log(a = a+5) 
// console.log(a % b)
// console.log(a^b)
// console.log(a ++)
// console.log(d = a !=b)
// console.log(a +=5)
// console.log(a > b)
// console.log(a<=b)
// console.log(a<=b)
// console.log(a<=b)
// console.log(a<=b)
// console.log(a<=b)
// console.log(a<=b)
let z = prompt("Name")
x = Number(prompt("number 1"))
y = Number(prompt("number 2"))
console.log
alert ("Hi    " + z)
alert ("sum     "  +(x+y))
alert ("умнож    " +(x*y))
alert ("-    "  +(x-y))
alert ("/     "  +(x/y))